services:
  app:
    env_file: ./.env
    container_name: ${APP_NAME}
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
      context: ./
    volumes:
      - ./src:/src
      - ./nodemon.json:/nodemon.json
