services:
  we-meet-backend:
    env_file: .env
    container_name: we-meet-backend
    restart: unless-stopped
    ports:
      - ${BACKEND_APP_PORT}:${BACKEND_APP_PORT}
    build:
      context: ./
    volumes:
      - ./src:/src
      - ./nodemon.json:/nodemon.json
